### ISSUE TITLE
can not run the code

### ISSUE THREAD

**Issue by tengshaofeng** [rwightman/tensorflow-litterbox#8]
@rwightman ,
i am so appreciated with your great job. i try to run imagenet_train.py, but it does not run correctly.
i do not know how to place the data. i have no idea of what type of data, and the architecture of data.

when i run to 'feed = FeedImagesWithLabels(dataset=dataset, processor=processor)'
it cames this  error:
![image](https://user-images.githubusercontent.com/9246739/26966402-7a6a48d4-4d2c-11e7-9c68-f7059494803f.png)

**Comment by rwightman** [comment]
It requires the Imagenet (or an Imagenet like dataset) to be encoded in sharded TF records format. 

The scripts required to convert the imagenet dataset into records is in https://github.com/rwightman/tensorflow-litterbox/tree/master/litterbox/data

Those scripts were taken from Google's earlier Inception network and preprocessing scripts at https://github.com/tensorflow/models/tree/master/inception/inception/data 

Since I wrote this code to learn about Tensorflow, Google themselves have released a number of the newer networks with trained weights that I built here including Inception V4 and Inception-Resnet V2. I'd recommend using them if you're looking to actual run the models vs a learning exercise: https://github.com/tensorflow/models/tree/master/slim/nets

My models are likely out of date/not working with the latest Tensorflow releases...
